# Generated by Django 5.1.7 on 2025-03-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("dataInicio", models.DateTimeField()),
                ("dataFim", models.DateTimeField()),
                ("local", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "estadoAtualAgenda",
                    models.CharField(
                        choices=[
                            ("RECEBIDO", "Recebido"),
                            ("CONFIRMADO", "Confirmado"),
                            ("ATENDIDO", "Atendido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="RECEBIDO",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-dataInicio"],
            },
        ),
    ]
