# Generated by Django 4.2.5 on 2025-03-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agenda",
            options={"ordering": ["dataInicio"]},
        ),
    ]
