# Generated by Django 4.2.5 on 2025-03-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0002_alter_agenda_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenda",
            name="estadoAtualAgenda",
            field=models.CharField(
                choices=[
                    ("RECEBIDO", "Recebido"),
                    ("CONFIRMADO", "Confirmado"),
                    ("CANCELADO", "Cancelado"),
                    ("ATENDIDO", "Atendido"),
                ],
                default="RECEBIDO",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="agenda",
            name="local",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="agenda",
            name="titulo",
            field=models.CharField(max_length=200),
        ),
    ]
